# Uncomment the next line to define a global platform for your project
 platform :ios, '10.2'

target 'weLearn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weLearn
  
pod 'SnapKit'
pod 'JSSAlertView'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'SwiftLinkPreview', '~> 1.0.1'

end
